POST http://localhost:8080/utilisateurs
Content-Type: application/json

{
    "nom": "Jean Dupont",
    "email": "jd43@hotmail.fr",
    "motDePasse": "motdepasse123"
}
###
DELETE http://localhost:8080/utilisateurs/1

###
GET http://localhost:8080/utilisateurs/2

###
PUT http://localhost:8080/utilisateurs/2
Content-Type: application/json

{
    "nom": "Jean Dupont",
    "email": "jp63@hotmail.fr",
    "motDePasse": "nouveaumotdepasse456"
}